import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// { children }: 这是对象解构语法。它从传递给函数的第一个参数对象中提取了一个名为 
// children 的属性，并将其赋值给局部变量 children。这允许你在函数内部直接使用 children 这个变量，
// 而不需要通过 props 对象来访问。

// : { children: React.ReactNode }: 这部分指定了对象参数的类型。它告诉 TypeScript，
// 传递给函数的对象参数必须具有一个名为 children 的属性，而且这个属性的类型必须是 React.ReactNode。
// 这是一种类型注解，有助于 TypeScript 在编译时检查代码的类型正确性。

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
